---
# set ft=yaml.ansible

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu1804
    image: sh0shin/ubuntu-18.04-python3:latest
    #volumes:
    privileged: true
    pre_build_image: true
  - name: ubuntu2004
    image: sh0shin/ubuntu-20.04-python3:latest
    #volumes:
    privileged: true
    pre_build_image: true
  - name: debian9
    image: sh0shin/debian-9-python3:latest
    #volumes:
    privileged: true
    pre_build_image: true
  - name: debian10
    image: sh0shin/debian-10-python3:latest
    #volumes:
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  ansible_args:
    - "-D"
  playbooks:
    converge: converge.yml
